name: Upload Python Package

on:
  push:
    # Push events to every tag including hierarchical tags like v1.0/beta
    tags:
      - '**'

jobs:
  deploy:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $(PYPI_TOKEN)
        TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
      run: |
        python -m build
        twine upload --skip-existing dist/*
